import React from 'react';
import {
  GoogleDriveIcon,
  GoogleDocsIcon,
  GoogleSheetsIcon,
  GoogleSlidesIcon,
  GoogleDrawingsIcon,
  GoogleSitesIcon,
  GmailIcon,
  GoogleMessagesIcon,
  GoogleCalendarIcon,
  GoogleTasksIcon,
  GoogleChatIcon,
  GoogleContactsIcon,
  GoogleMeetIcon,
  GoogleFormsIcon,
  GoogleKeepIcon,
  GooglePhotosIcon,
  YouTubeStudioIcon,
  GoogleAnalyticsIcon,
  GoogleSearchConsoleIcon,
  GoogleTrendsIcon,
  GoogleFinanceIcon,
  GoogleMapsIcon,
  GoogleTranslateIcon,
  GoogleClassroomIcon,
  GoogleLogo,
} from '../components/GoogleIcons';

export interface ToolDefinition {
  id: string;
  name: string;
  shortName: string;
  category: 'Communication' | 'Creation' | 'Planning' | 'Media & Utilities' | 'Business & Insights';
  desc: string;
  icon: React.FC<{ className?: string; alt?: string }>;
  accent: string;
  badge: string;
  badgeColor: string;
  webUrl: string;
  defaultPinned?: boolean;
}

export const ALL_WORKSPACE_TOOLS: ToolDefinition[] = [
  // Communication
  {
    id: 'gmail',
    name: 'Gmail',
    shortName: 'Gmail',
    category: 'Communication',
    desc: 'Real-time inbox, AI thread drafts & sender sync',
    icon: GmailIcon,
    accent: 'hover:border-red-500/40 hover:shadow-red-500/10',
    badge: 'Inbox',
    badgeColor: 'bg-red-500/10 text-red-500 border-red-500/20',
    webUrl: 'https://mail.google.com',
    defaultPinned: true,
  },
  {
    id: 'messages',
    name: 'Google Messages',
    shortName: 'Messages',
    category: 'Communication',
    desc: 'Text, RCS chats & Android synced SMS',
    icon: GoogleMessagesIcon,
    accent: 'hover:border-blue-500/40 hover:shadow-blue-500/10',
    badge: 'SMS / RCS',
    badgeColor: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
    webUrl: 'https://messages.google.com/web',
    defaultPinned: true,
  },
  {
    id: 'meet',
    name: 'Google Meet',
    shortName: 'Meet',
    category: 'Communication',
    desc: 'Instant video conferences & space generator',
    icon: GoogleMeetIcon,
    accent: 'hover:border-teal-500/40 hover:shadow-teal-500/10',
    badge: 'HD Video',
    badgeColor: 'bg-teal-500/10 text-teal-500 border-teal-500/20',
    webUrl: 'https://meet.google.com',
    defaultPinned: false,
  },
  {
    id: 'chat',
    name: 'Google Chat',
    shortName: 'Chat',
    category: 'Communication',
    desc: 'Team spaces & direct collaborative messages',
    icon: GoogleChatIcon,
    accent: 'hover:border-emerald-600/40 hover:shadow-emerald-600/10',
    badge: 'Spaces',
    badgeColor: 'bg-emerald-500/10 text-emerald-500 border-emerald-500/20',
    webUrl: 'https://chat.google.com',
    defaultPinned: false,
  },
  {
    id: 'contacts',
    name: 'Google Contacts',
    shortName: 'Contacts',
    category: 'Communication',
    desc: 'Directory, address book & colleague details',
    icon: GoogleContactsIcon,
    accent: 'hover:border-blue-600/40 hover:shadow-blue-600/10',
    badge: 'Directory',
    badgeColor: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
    webUrl: 'https://contacts.google.com',
    defaultPinned: false,
  },

  // Creation & Docs
  {
    id: 'drive',
    name: 'Google Drive',
    shortName: 'Drive',
    category: 'Creation',
    desc: 'Cloud storage, docs & media repository',
    icon: GoogleDriveIcon,
    accent: 'hover:border-amber-500/40 hover:shadow-amber-500/10',
    badge: 'Cloud Storage',
    badgeColor: 'bg-amber-500/10 text-amber-500 border-amber-500/20',
    webUrl: 'https://drive.google.com',
    defaultPinned: true,
  },
  {
    id: 'docs',
    name: 'Google Docs',
    shortName: 'Docs',
    category: 'Creation',
    desc: 'Collaborative word processing & rich text editor',
    icon: GoogleDocsIcon,
    accent: 'hover:border-blue-500/40 hover:shadow-blue-500/10',
    badge: 'Documents',
    badgeColor: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
    webUrl: 'https://docs.google.com',
    defaultPinned: true,
  },
  {
    id: 'sheets',
    name: 'Google Sheets',
    shortName: 'Sheets',
    category: 'Creation',
    desc: 'Live spreadsheets, calculations & data grid',
    icon: GoogleSheetsIcon,
    accent: 'hover:border-emerald-500/40 hover:shadow-emerald-500/10',
    badge: 'Spreadsheets',
    badgeColor: 'bg-emerald-500/10 text-emerald-500 border-emerald-500/20',
    webUrl: 'https://sheets.google.com',
    defaultPinned: true,
  },
  {
    id: 'slides',
    name: 'Google Slides',
    shortName: 'Slides',
    category: 'Creation',
    desc: 'Presentations, deck builder & slide templates',
    icon: GoogleSlidesIcon,
    accent: 'hover:border-amber-500/40 hover:shadow-amber-500/10',
    badge: 'Presentations',
    badgeColor: 'bg-amber-500/10 text-amber-500 border-amber-500/20',
    webUrl: 'https://slides.google.com',
    defaultPinned: false,
  },
  {
    id: 'drawings',
    name: 'Google Drawings',
    shortName: 'Drawings',
    category: 'Creation',
    desc: 'Vector graphics, diagrams, flowcharts & sketches',
    icon: GoogleDrawingsIcon,
    accent: 'hover:border-red-500/40 hover:shadow-red-500/10',
    badge: 'Vector Canvas',
    badgeColor: 'bg-red-500/10 text-red-500 border-red-500/20',
    webUrl: 'https://docs.google.com/drawings',
    defaultPinned: false,
  },
  {
    id: 'forms',
    name: 'Google Forms',
    shortName: 'Forms',
    category: 'Creation',
    desc: 'Questionnaires, surveys & response charts',
    icon: GoogleFormsIcon,
    accent: 'hover:border-purple-500/40 hover:shadow-purple-500/10',
    badge: 'Surveys',
    badgeColor: 'bg-purple-500/10 text-purple-500 border-purple-500/20',
    webUrl: 'https://forms.google.com',
    defaultPinned: false,
  },
  {
    id: 'sites',
    name: 'Google Sites',
    shortName: 'Sites',
    category: 'Creation',
    desc: 'Team portals, company wikis & intranet pages',
    icon: GoogleSitesIcon,
    accent: 'hover:border-indigo-500/40 hover:shadow-indigo-500/10',
    badge: 'Intranet',
    badgeColor: 'bg-indigo-500/10 text-indigo-500 border-indigo-500/20',
    webUrl: 'https://sites.google.com',
    defaultPinned: false,
  },
  {
    id: 'keep',
    name: 'Google Keep',
    shortName: 'Keep',
    category: 'Creation',
    desc: 'Fast scratchpad, checklists & colored notes',
    icon: GoogleKeepIcon,
    accent: 'hover:border-yellow-500/40 hover:shadow-yellow-500/10',
    badge: 'Notes',
    badgeColor: 'bg-yellow-500/10 text-yellow-500 border-yellow-500/20',
    webUrl: 'https://keep.google.com',
    defaultPinned: false,
  },

  // Planning & Productivity
  {
    id: 'calendar',
    name: 'Google Calendar',
    shortName: 'Calendar',
    category: 'Planning',
    desc: 'Schedules, meetings & time-blocking',
    icon: GoogleCalendarIcon,
    accent: 'hover:border-blue-500/40 hover:shadow-blue-500/10',
    badge: 'Schedule',
    badgeColor: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
    webUrl: 'https://calendar.google.com',
    defaultPinned: true,
  },
  {
    id: 'tasks',
    name: 'Google Tasks',
    shortName: 'Tasks',
    category: 'Planning',
    desc: 'To-do lists, deadlines & completion tracking',
    icon: GoogleTasksIcon,
    accent: 'hover:border-sky-500/40 hover:shadow-sky-500/10',
    badge: 'To-Dos',
    badgeColor: 'bg-sky-500/10 text-sky-500 border-sky-500/20',
    webUrl: 'https://tasks.google.com',
    defaultPinned: true,
  },
  {
    id: 'classroom',
    name: 'Google Classroom',
    shortName: 'Classroom',
    category: 'Planning',
    desc: 'Course management, assignment streams & grading',
    icon: GoogleClassroomIcon,
    accent: 'hover:border-emerald-600/40 hover:shadow-emerald-600/10',
    badge: 'Education',
    badgeColor: 'bg-emerald-500/10 text-emerald-500 border-emerald-500/20',
    webUrl: 'https://classroom.google.com',
    defaultPinned: false,
  },

  // Media & Utilities
  {
    id: 'photos',
    name: 'Google Photos',
    shortName: 'Photos',
    category: 'Media & Utilities',
    desc: 'Photo albums, cloud backups & visual search',
    icon: GooglePhotosIcon,
    accent: 'hover:border-amber-500/40 hover:shadow-amber-500/10',
    badge: 'Gallery',
    badgeColor: 'bg-amber-500/10 text-amber-500 border-amber-500/20',
    webUrl: 'https://photos.google.com',
    defaultPinned: false,
  },
  {
    id: 'youtube',
    name: 'YouTube Studio',
    shortName: 'YouTube',
    category: 'Media & Utilities',
    desc: 'Video uploads, channel metrics & subscriber insights',
    icon: YouTubeStudioIcon,
    accent: 'hover:border-red-500/40 hover:shadow-red-500/10',
    badge: 'Video & Creator',
    badgeColor: 'bg-red-500/10 text-red-500 border-red-500/20',
    webUrl: 'https://studio.youtube.com',
    defaultPinned: false,
  },
  {
    id: 'maps',
    name: 'Google Maps',
    shortName: 'Maps',
    category: 'Media & Utilities',
    desc: 'Campus locations, route navigation & place details',
    icon: GoogleMapsIcon,
    accent: 'hover:border-blue-500/40 hover:shadow-blue-500/10',
    badge: 'Navigation',
    badgeColor: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
    webUrl: 'https://maps.google.com',
    defaultPinned: false,
  },
  {
    id: 'translate',
    name: 'Google Translate',
    shortName: 'Translate',
    category: 'Media & Utilities',
    desc: 'Multi-language neural translation & voice audio',
    icon: GoogleTranslateIcon,
    accent: 'hover:border-blue-500/40 hover:shadow-blue-500/10',
    badge: 'Language AI',
    badgeColor: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
    webUrl: 'https://translate.google.com',
    defaultPinned: false,
  },

  // Business & Insights
  {
    id: 'analytics',
    name: 'Google Analytics',
    shortName: 'Analytics',
    category: 'Business & Insights',
    desc: 'Live web traffic, conversion funnels & user engagement',
    icon: GoogleAnalyticsIcon,
    accent: 'hover:border-amber-500/40 hover:shadow-amber-500/10',
    badge: 'Web Metrics',
    badgeColor: 'bg-amber-500/10 text-amber-500 border-amber-500/20',
    webUrl: 'https://analytics.google.com',
    defaultPinned: false,
  },
  {
    id: 'searchconsole',
    name: 'Google Search Console',
    shortName: 'Search Console',
    category: 'Business & Insights',
    desc: 'Organic search clicks, query rankings & site indexing',
    icon: GoogleSearchConsoleIcon,
    accent: 'hover:border-blue-500/40 hover:shadow-blue-500/10',
    badge: 'Search SEO',
    badgeColor: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
    webUrl: 'https://search.google.com/search-console',
    defaultPinned: false,
  },
  {
    id: 'trends',
    name: 'Google Trends',
    shortName: 'Trends',
    category: 'Business & Insights',
    desc: 'Global search interest curves & breakout topic spikes',
    icon: GoogleTrendsIcon,
    accent: 'hover:border-blue-500/40 hover:shadow-blue-500/10',
    badge: 'Market Trends',
    badgeColor: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
    webUrl: 'https://trends.google.com',
    defaultPinned: false,
  },
  {
    id: 'finance',
    name: 'Google Finance',
    shortName: 'Finance',
    category: 'Business & Insights',
    desc: 'Live stock ticker quotes, market indexes & portfolio watch',
    icon: GoogleFinanceIcon,
    accent: 'hover:border-emerald-500/40 hover:shadow-emerald-500/10',
    badge: 'Markets',
    badgeColor: 'bg-emerald-500/10 text-emerald-500 border-emerald-500/20',
    webUrl: 'https://finance.google.com',
    defaultPinned: false,
  },
];

export const CATEGORIES = [
  'Communication',
  'Creation',
  'Planning',
  'Media & Utilities',
  'Business & Insights',
] as const;

export const DEFAULT_PINNED_TOOL_IDS = ALL_WORKSPACE_TOOLS.filter((t) => t.defaultPinned).map((t) => t.id);
