import React from 'react';
import {
  GoogleDriveIcon,
  GoogleDocsIcon,
  GoogleSheetsIcon,
  GoogleSlidesIcon,
  GmailIcon,
  GoogleCalendarIcon,
  GoogleTasksIcon,
  GoogleMeetIcon,
  GoogleFormsIcon,
  GoogleKeepIcon,
  GoogleChatIcon,
  GoogleContactsIcon,
  GoogleMessagesIcon,
  GoogleClassroomIcon,
  GoogleSitesIcon,
  GoogleDrawingsIcon,
  GooglePhotosIcon,
  GoogleMapsIcon,
  YouTubeStudioIcon,
  GoogleAnalyticsIcon,
  GoogleSearchConsoleIcon,
  GoogleTrendsIcon,
  GoogleFinanceIcon,
  GoogleTranslateIcon,
} from '../components/GoogleIcons';

export type WorkspaceCategory = 'Communication' | 'Creation & Docs' | 'Planning & Notes';

export interface ToolDefinition {
  id: string;
  name: string;
  shortName: string;
  category: WorkspaceCategory;
  desc: string;
  icon: React.FC<{ className?: string; alt?: string }>;
  accent: string;
  badge: string;
  badgeColor: string;
  webUrl: string;
  defaultPinned?: boolean;
}

export const ALL_WORKSPACE_TOOLS: ToolDefinition[] = [
  // 1. Gmail
  {
    id: 'gmail',
    name: 'Gmail',
    shortName: 'Gmail',
    category: 'Communication',
    desc: 'Unified inbox, compose messages, smart threads & email search',
    icon: GmailIcon,
    accent: 'hover:border-red-500/40 hover:shadow-red-500/10',
    badge: 'Inbox & Mail',
    badgeColor: 'bg-red-500/10 text-red-500 border-red-500/20',
    webUrl: 'https://mail.google.com',
    defaultPinned: true,
  },
  // 2. Google Drive
  {
    id: 'drive',
    name: 'Google Drive',
    shortName: 'Drive',
    category: 'Creation & Docs',
    desc: 'Cloud file storage, folder organization & upload repository',
    icon: GoogleDriveIcon,
    accent: 'hover:border-amber-500/40 hover:shadow-amber-500/10',
    badge: 'Cloud Storage',
    badgeColor: 'bg-amber-500/10 text-amber-500 border-amber-500/20',
    webUrl: 'https://drive.google.com',
    defaultPinned: true,
  },
  // 3. Google Docs
  {
    id: 'docs',
    name: 'Google Docs',
    shortName: 'Docs',
    category: 'Creation & Docs',
    desc: 'Collaborative word processing, rich text formatting & templates',
    icon: GoogleDocsIcon,
    accent: 'hover:border-blue-500/40 hover:shadow-blue-500/10',
    badge: 'Documents',
    badgeColor: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
    webUrl: 'https://docs.google.com',
    defaultPinned: true,
  },
  // 4. Google Sheets
  {
    id: 'sheets',
    name: 'Google Sheets',
    shortName: 'Sheets',
    category: 'Creation & Docs',
    desc: 'Spreadsheets, formula calculations, live data grid & analysis',
    icon: GoogleSheetsIcon,
    accent: 'hover:border-emerald-500/40 hover:shadow-emerald-500/10',
    badge: 'Spreadsheets',
    badgeColor: 'bg-emerald-500/10 text-emerald-500 border-emerald-500/20',
    webUrl: 'https://sheets.google.com',
    defaultPinned: true,
  },
  // 5. Google Calendar
  {
    id: 'calendar',
    name: 'Google Calendar',
    shortName: 'Calendar',
    category: 'Planning & Notes',
    desc: 'Schedules, meetings, time-blocking & event agendas',
    icon: GoogleCalendarIcon,
    accent: 'hover:border-blue-500/40 hover:shadow-blue-500/10',
    badge: 'Schedule',
    badgeColor: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
    webUrl: 'https://calendar.google.com',
    defaultPinned: true,
  },
  // 6. Google Meet
  {
    id: 'meet',
    name: 'Google Meet',
    shortName: 'Meet',
    category: 'Communication',
    desc: 'Instant HD video conferences, call rooms & meeting spaces',
    icon: GoogleMeetIcon,
    accent: 'hover:border-teal-500/40 hover:shadow-teal-500/10',
    badge: 'HD Video',
    badgeColor: 'bg-teal-500/10 text-teal-500 border-teal-500/20',
    webUrl: 'https://meet.google.com',
    defaultPinned: true,
  },
  // 7. Google Slides
  {
    id: 'slides',
    name: 'Google Slides',
    shortName: 'Slides',
    category: 'Creation & Docs',
    desc: 'Presentations, pitch decks, slide layouts & presenter view',
    icon: GoogleSlidesIcon,
    accent: 'hover:border-amber-500/40 hover:shadow-amber-500/10',
    badge: 'Presentations',
    badgeColor: 'bg-amber-500/10 text-amber-500 border-amber-500/20',
    webUrl: 'https://slides.google.com',
    defaultPinned: true,
  },
  // 8. Google Forms
  {
    id: 'forms',
    name: 'Google Forms',
    shortName: 'Forms',
    category: 'Creation & Docs',
    desc: 'Online surveys, questionnaires, polls & response analysis',
    icon: GoogleFormsIcon,
    accent: 'hover:border-purple-500/40 hover:shadow-purple-500/10',
    badge: 'Surveys & Forms',
    badgeColor: 'bg-purple-500/10 text-purple-500 border-purple-500/20',
    webUrl: 'https://forms.google.com',
    defaultPinned: true,
  },
  // 9. Google Keep
  {
    id: 'keep',
    name: 'Google Keep',
    shortName: 'Keep',
    category: 'Planning & Notes',
    desc: 'Quick scratchpad notes, colored sticky cards & pinned ideas',
    icon: GoogleKeepIcon,
    accent: 'hover:border-yellow-500/40 hover:shadow-yellow-500/10',
    badge: 'Notes & Ideas',
    badgeColor: 'bg-yellow-500/10 text-yellow-500 border-yellow-500/20',
    webUrl: 'https://keep.google.com',
    defaultPinned: true,
  },
  // 10. Google Tasks
  {
    id: 'tasks',
    name: 'Google Tasks',
    shortName: 'Tasks',
    category: 'Planning & Notes',
    desc: 'Action items, daily checklists, deadlines & to-do tracking',
    icon: GoogleTasksIcon,
    accent: 'hover:border-sky-500/40 hover:shadow-sky-500/10',
    badge: 'Action Items',
    badgeColor: 'bg-sky-500/10 text-sky-500 border-sky-500/20',
    webUrl: 'https://tasks.google.com',
    defaultPinned: true,
  },
  // 11. Google Chat
  {
    id: 'chat',
    name: 'Google Chat',
    shortName: 'Chat',
    category: 'Communication',
    desc: 'Team channels, direct messaging, spaces & instant collaborative chats',
    icon: GoogleChatIcon,
    accent: 'hover:border-teal-500/40 hover:shadow-teal-500/10',
    badge: 'Team Messaging',
    badgeColor: 'bg-teal-500/10 text-teal-500 border-teal-500/20',
    webUrl: 'https://chat.google.com',
    defaultPinned: false,
  },
  // 12. Google Contacts
  {
    id: 'contacts',
    name: 'Google Contacts',
    shortName: 'Contacts',
    category: 'Communication',
    desc: 'Directory, client contact cards, phone numbers & email groups',
    icon: GoogleContactsIcon,
    accent: 'hover:border-blue-500/40 hover:shadow-blue-500/10',
    badge: 'Directory',
    badgeColor: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
    webUrl: 'https://contacts.google.com',
    defaultPinned: false,
  },
  // 13. Google Messages
  {
    id: 'messages',
    name: 'Google Messages',
    shortName: 'Messages',
    category: 'Communication',
    desc: 'RCS/SMS messaging, phone synchronization & chat threads',
    icon: GoogleMessagesIcon,
    accent: 'hover:border-blue-500/40 hover:shadow-blue-500/10',
    badge: 'RCS & SMS',
    badgeColor: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
    webUrl: 'https://messages.google.com/web',
    defaultPinned: false,
  },
  // 14. Google Translate
  {
    id: 'translate',
    name: 'Google Translate',
    shortName: 'Translate',
    category: 'Communication',
    desc: 'Instant translation in 100+ languages with text & voice detection',
    icon: GoogleTranslateIcon,
    accent: 'hover:border-blue-500/40 hover:shadow-blue-500/10',
    badge: 'Languages',
    badgeColor: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
    webUrl: 'https://translate.google.com',
    defaultPinned: false,
  },
  // 15. Google Classroom
  {
    id: 'classroom',
    name: 'Google Classroom',
    shortName: 'Classroom',
    category: 'Planning & Notes',
    desc: 'Course management, student assignments, grading & school resources',
    icon: GoogleClassroomIcon,
    accent: 'hover:border-emerald-500/40 hover:shadow-emerald-500/10',
    badge: 'Education',
    badgeColor: 'bg-emerald-500/10 text-emerald-500 border-emerald-500/20',
    webUrl: 'https://classroom.google.com',
    defaultPinned: false,
  },
  // 16. Google Maps
  {
    id: 'maps',
    name: 'Google Maps',
    shortName: 'Maps',
    category: 'Planning & Notes',
    desc: 'Navigation, real-time traffic, business directories & routes',
    icon: GoogleMapsIcon,
    accent: 'hover:border-emerald-500/40 hover:shadow-emerald-500/10',
    badge: 'Navigation',
    badgeColor: 'bg-emerald-500/10 text-emerald-500 border-emerald-500/20',
    webUrl: 'https://maps.google.com',
    defaultPinned: false,
  },
  // 17. Google Finance
  {
    id: 'finance',
    name: 'Google Finance',
    shortName: 'Finance',
    category: 'Planning & Notes',
    desc: 'Stock market quotes, watchlists, currency rates & financial trends',
    icon: GoogleFinanceIcon,
    accent: 'hover:border-emerald-500/40 hover:shadow-emerald-500/10',
    badge: 'Markets',
    badgeColor: 'bg-emerald-500/10 text-emerald-500 border-emerald-500/20',
    webUrl: 'https://www.google.com/finance',
    defaultPinned: false,
  },
  // 18. Google Trends
  {
    id: 'trends',
    name: 'Google Trends',
    shortName: 'Trends',
    category: 'Planning & Notes',
    desc: 'Global search volume, trending keywords & geographic interest',
    icon: GoogleTrendsIcon,
    accent: 'hover:border-blue-500/40 hover:shadow-blue-500/10',
    badge: 'Search Trends',
    badgeColor: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
    webUrl: 'https://trends.google.com',
    defaultPinned: false,
  },
  // 19. Google Sites
  {
    id: 'sites',
    name: 'Google Sites',
    shortName: 'Sites',
    category: 'Creation & Docs',
    desc: 'Intranet hubs, project pages, team wikis & public websites',
    icon: GoogleSitesIcon,
    accent: 'hover:border-blue-500/40 hover:shadow-blue-500/10',
    badge: 'Web Portals',
    badgeColor: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
    webUrl: 'https://sites.google.com',
    defaultPinned: false,
  },
  // 20. Google Drawings
  {
    id: 'drawings',
    name: 'Google Drawings',
    shortName: 'Drawings',
    category: 'Creation & Docs',
    desc: 'Vector graphics, system flowcharts, diagrams & visual layouts',
    icon: GoogleDrawingsIcon,
    accent: 'hover:border-red-500/40 hover:shadow-red-500/10',
    badge: 'Vector Graphics',
    badgeColor: 'bg-red-500/10 text-red-500 border-red-500/20',
    webUrl: 'https://drawings.google.com',
    defaultPinned: false,
  },
  // 21. Google Photos
  {
    id: 'photos',
    name: 'Google Photos',
    shortName: 'Photos',
    category: 'Creation & Docs',
    desc: 'Visual memory vault, smart photo search & cloud album backup',
    icon: GooglePhotosIcon,
    accent: 'hover:border-red-500/40 hover:shadow-red-500/10',
    badge: 'Photo Library',
    badgeColor: 'bg-red-500/10 text-red-500 border-red-500/20',
    webUrl: 'https://photos.google.com',
    defaultPinned: false,
  },
  // 22. YouTube Studio
  {
    id: 'youtube',
    name: 'YouTube Studio',
    shortName: 'YouTube',
    category: 'Creation & Docs',
    desc: 'Video publishing, audience statistics, comments & media management',
    icon: YouTubeStudioIcon,
    accent: 'hover:border-red-600/40 hover:shadow-red-600/10',
    badge: 'Video & Media',
    badgeColor: 'bg-red-600/10 text-red-600 border-red-600/20',
    webUrl: 'https://studio.youtube.com',
    defaultPinned: false,
  },
  // 23. Google Analytics
  {
    id: 'analytics',
    name: 'Google Analytics',
    shortName: 'Analytics',
    category: 'Creation & Docs',
    desc: 'Traffic measurement, audience reports & marketing performance',
    icon: GoogleAnalyticsIcon,
    accent: 'hover:border-amber-500/40 hover:shadow-amber-500/10',
    badge: 'Analytics',
    badgeColor: 'bg-amber-500/10 text-amber-500 border-amber-500/20',
    webUrl: 'https://analytics.google.com',
    defaultPinned: false,
  },
  // 24. Google Search Console
  {
    id: 'searchconsole',
    name: 'Google Search Console',
    shortName: 'Console',
    category: 'Creation & Docs',
    desc: 'Search performance, index coverage, organic queries & site health',
    icon: GoogleSearchConsoleIcon,
    accent: 'hover:border-blue-500/40 hover:shadow-blue-500/10',
    badge: 'SEO & Search',
    badgeColor: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
    webUrl: 'https://search.google.com/search-console',
    defaultPinned: false,
  },
];

export const CATEGORIES = [
  'Communication',
  'Creation & Docs',
  'Planning & Notes',
] as const;

export const DEFAULT_PINNED_TOOL_IDS = [
  'gmail',
  'drive',
  'docs',
  'sheets',
  'calendar',
  'meet',
  'slides',
  'forms',
  'keep',
  'tasks',
];
